// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Task struct {
	Taskid   int32          `json:"taskid"`
	Taskname sql.NullString `json:"taskname"`
	Tasktime sql.NullString `json:"tasktime"`
	Taskdate sql.NullString `json:"taskdate"`
}
